-- Insert sample podcasts
INSERT INTO podcasts (
  title,
  description,
  episode_number,
  category,
  image_url,
  audio_url,
  duration,
  host,
  guests,
  published_at,
  featured,
  listen_count
) VALUES
(
  'The Future of Economic Freedom in Nigeria',
  'Join us as we discuss the challenges and opportunities for economic freedom in Nigeria, featuring insights from leading economists and entrepreneurs.',
  1,
  'FREEDOM',
  'https://images.unsplash.com/photo-1559526324-593bc073d938?q=80&w=2070',
  'https://storage.googleapis.com/fff-podcasts/episode1.mp3',
  '45:00',
  'John Doe',
  ARRAY['Jane Smith', 'Michael Johnson'],
  '2024-03-15',
  true,
  1200
),
(
  'Youth Leadership in the Digital Age',
  'Exploring how young Nigerians are leveraging technology to create positive change and lead the next generation of freedom advocates.',
  2,
  'LEADERSHIP',
  'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=2071',
  'https://storage.googleapis.com/fff-podcasts/episode2.mp3',
  '38:30',
  'Sarah Williams',
  ARRAY['David Brown', 'Emily Chen'],
  '2024-03-10',
  false,
  850
),
(
  'Policy Reform: A Path to Prosperity',
  'An in-depth discussion on policy reforms needed to unlock Nigeria''s economic potential and create opportunities for all.',
  3,
  'ADVOCACY',
  'https://images.unsplash.com/photo-1573164713988-8665fc963095?q=80&w=2069',
  'https://storage.googleapis.com/fff-podcasts/episode3.mp3',
  '52:15',
  'Michael Johnson',
  ARRAY['Robert Wilson', 'Lisa Anderson'],
  '2024-03-05',
  false,
  950
),
(
  'Global Perspectives on Freedom',
  'Connecting with freedom advocates from around the world to share insights and strategies for promoting liberty.',
  4,
  'GLOBAL',
  'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=2070',
  'https://storage.googleapis.com/fff-podcasts/episode4.mp3',
  '41:45',
  'Emma Thompson',
  ARRAY['James Wilson', 'Maria Garcia'],
  '2024-03-01',
  false,
  780
),
(
  'Entrepreneurship: The Engine of Growth',
  'Discover how entrepreneurship is driving economic growth and creating opportunities for young Nigerians.',
  5,
  'FREEDOM',
  'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=2070',
  'https://storage.googleapis.com/fff-podcasts/episode5.mp3',
  '47:20',
  'John Doe',
  ARRAY['Peter Chen', 'Sarah Williams'],
  '2024-02-25',
  false,
  1100
),
(
  'Building Tomorrow''s Leaders Today',
  'A conversation about developing leadership skills and creating a pipeline of future freedom advocates.',
  6,
  'LEADERSHIP',
  'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=2070',
  'https://storage.googleapis.com/fff-podcasts/episode6.mp3',
  '39:15',
  'Sarah Williams',
  ARRAY['David Brown', 'Michael Johnson'],
  '2024-02-20',
  false,
  920
),
(
  'The Role of Civil Society in Policy Change',
  'Examining how civil society organizations can effectively advocate for policy reforms that promote freedom.',
  7,
  'ADVOCACY',
  'https://images.unsplash.com/photo-1521791136064-7986c2920216?q=80&w=2069',
  'https://storage.googleapis.com/fff-podcasts/episode7.mp3',
  '44:30',
  'Michael Johnson',
  ARRAY['Emma Thompson', 'Robert Wilson'],
  '2024-02-15',
  false,
  890
),
(
  'Freedom Movements Around the World',
  'Learning from successful freedom movements in other countries and applying those lessons to Nigeria.',
  8,
  'GLOBAL',
  'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=2071',
  'https://storage.googleapis.com/fff-podcasts/episode8.mp3',
  '50:00',
  'Emma Thompson',
  ARRAY['James Wilson', 'Maria Garcia'],
  '2024-02-10',
  false,
  750
); 